"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Take environment variables from .env file
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-g-v834+yv$1%h&gmgy_0c$peejr$zwamo*4(hk!da&*5=c&%o*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])
if DEBUG:
    ALLOWED_HOSTS = ['*']

# --- SÉCURITÉ AVANCÉE & PROXY ---
if not DEBUG:
    # HSTS
    SECURE_HSTS_SECONDS = 31536000 # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Redirection HTTPS et Cookies derrière Proxy (Cloudflare, DigitalOcean)
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Headers de protection
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY' # Empêche le clickjacking
    
    # Referrer Policy
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # CSRF Trusted Origins
    CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['https://*.dorocaviar.com', 'https://*.ondigitalocean.app'])

# Configuration CKEDITOR pour la sécurité
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'extraPlugins': ','.join(['codesnippet', 'youtube']),
    },
}

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    
    # 3rd Party
    'taggit',
    'autoslug',
    'ckeditor',
    'corsheaders',
    
    # Apps
    'apps.videos',
    'apps.users',
    'apps.marketing',
    'apps.blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
#                'apps.marketing.context_processors.platform_context',
                'apps.users.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR}/db.sqlite3')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


STATIC_URL = env('STATIC_URL', default='static/')
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA Configuration - Ready for CDN / Support Bunny.net Storage & CDN in Production
USE_BUNNY = env.bool('USE_BUNNY', default=False)
if USE_BUNNY:
    # Bunny.net S3-compatible credentials
    AWS_ACCESS_KEY_ID = env('BUNNY_STORAGE_ZONE_NAME')
    AWS_SECRET_ACCESS_KEY = env('BUNNY_STORAGE_PASSWORD')
    AWS_STORAGE_BUCKET_NAME = env('BUNNY_STORAGE_ZONE_NAME')
    
    # Endpoint Bunny S3 (ex: https://storage.bunnycdn.com)
    AWS_S3_ENDPOINT_URL = env('BUNNY_STORAGE_ENDPOINT', default='https://storage.bunnycdn.com')
    
    # Nom de domaine de votre Pull Zone BunnyCDN
    AWS_S3_CUSTOM_DOMAIN = env('BUNNY_CDN_DOMAIN')
    
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    
    # Media Storage
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        }
    }
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    
    # Optionnel: Servir aussi les fichiers statiques via BunnyCDN
    USE_BUNNY_STATIC = env.bool('USE_BUNNY_STATIC', default=False)
    if USE_BUNNY_STATIC:
        STORAGES["staticfiles"] = {
            "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
        }
        STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
else:
    MEDIA_URL = env('MEDIA_URL', default='media/')
    MEDIA_ROOT = BASE_DIR / 'media'

# Authentication
AUTH_USER_MODEL = 'users.User'

# Celery & Redis
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Email Configuration (SendGrid)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'  # Toujours 'apikey' pour SendGrid
EMAIL_HOST_PASSWORD = env('SENDGRID_API_KEY', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@dorocaviar.com')

# Caching (Redis Support for Production)
REDIS_URL = env('REDIS_URL', default=None)
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
    # Utiliser le cache Redis pour stocker les sessions utilisateurs
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JAZZMIN CONFIGURATION (Admin Theme)
JAZZMIN_SETTINGS = {
    "site_title": "DORO CAVIAR Admin",
    "site_header": "DORO CAVIAR",
    "site_brand": "Super Admin",
    "welcome_sign": "Bienvenue sur l'administration DORO CAVIAR",
    "copyright": "DORO CAVIAR Platform",
    "search_model": ["videos.Video", "users.User"],
    "show_ui_builder": False,
    "topmenu_links": [
        {"name": "Tableau de Bord",  "url": "admin:index"},
        {"name": "Statistiques Business", "url": "admin_stats"},
        {"name": "Voir le site public", "url": "/", "new_window": True},
    ],
    "icons": {
        "auth.Group": "fas fa-users-cog",
        "users.User": "fas fa-user",
        "videos.Video": "fas fa-video",
        "videos.Category": "fas fa-list-alt",
        "videos.ImportSource": "fas fa-cloud-download-alt",
        "marketing.Advertisement": "fas fa-ad",
        "marketing.AffiliateLink": "fas fa-link",
        "marketing.Page": "fas fa-file-alt",
        "marketing.PlatformSettings": "fas fa-cogs",
    },
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "accent": "accent-danger", # Accents rouges/roses pour Dorocaviar
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "sidebar": "sidebar-dark-danger",
    "sidebar_nav_flat_style": True,
    "brand_colour": "navbar-danger",
    "button_classes": {
        "primary": "btn-danger",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-danger",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
