# Generated by Django 6.0.4 on 2026-04-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_likes_video_uploader_alter_video_tags_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='affiliate_link',
            field=models.URLField(blank=True, help_text="Lien d'affiliation spécifique pour cette catégorie (utilisé pour les clics invisibles).", null=True),
        ),
    ]
