# Generated by Django 5.1.6 on 2026-04-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_short',
            field=models.BooleanField(default=False, help_text='Format vertical (9:16) type Reels/TikTok'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploader un fichier vidéo direct', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.URLField(blank=True, help_text='Ou coller un lien externe (YouTube, etc.)', null=True),
        ),
    ]
