# Generated by Django 6.0.4 on 2026-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_is_short_video_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.TextField(blank=True, help_text="Coller un lien ou le code d'intégration iframe complet", null=True),
        ),
    ]
