# Generated by Django 6.0.4 on 2026-05-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='anonymous_likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
