# Generated by Django 6.0.4 on 2026-04-20 17:52

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('content', models.TextField(help_text='Le contenu HTML de la page')),
                ('is_published', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Dorocaviar', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('ad_clicks_before_video', models.PositiveIntegerField(default=0, help_text='Nombre de clics sur le player/pub requis avant de pouvoir lancer la vidéo (0 = pas de restriction)')),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='html_content',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('BANNER', 'Banner (Image/HTML)'), ('POPUNDER', 'Pop-under (JS)'), ('INTERSTITIAL', 'Interstitial / Overlay (JS)')], default='BANNER', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='code',
            field=models.TextField(default='', help_text='Code JS, Iframe ou HTML fourni par la régie publicitaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='frequency_cap',
            field=models.PositiveIntegerField(default=0, help_text="Limiter l'affichage: X vues par utilisateur (0 = toujours afficher)"),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text="Priorité d'affichage (plus c'est élevé, plus ça s'affiche souvent)"),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optionnel: si vous uploadez votre propre bannière', null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True, help_text="Optionnel: lien de redirection si vous utilisez l'image ci-dessus"),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('GLOBAL_TOP', 'Global - Top Header'), ('GLOBAL_BOTTOM', 'Global - Bottom Footer'), ('SIDEBAR', 'Sidebar Column'), ('VIDEO_PLAYER_OVERLAY', 'Over the Video Player'), ('BACKGROUND', 'Background/Popunder script')], max_length=25),
        ),
        migrations.AlterField(
            model_name='affiliatelink',
            name='original_url',
            field=models.URLField(help_text="Le vrai lien fourni par la plateforme d'affiliation"),
        ),
        migrations.AlterField(
            model_name='affiliatelink',
            name='tracking_url',
            field=models.URLField(help_text="L'URL propre sur votre site qui redirigera vers l'affiliation", unique=True),
        ),
    ]
