# Generated by Django 6.0.4 on 2026-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_menulink'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='invisible_ad_active',
            field=models.BooleanField(default=False, help_text='Activer la couche de liens invisibles (Ghost Layer) sur le lecteur.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='invisible_ad_link',
            field=models.URLField(blank=True, help_text="Le lien d'affiliation vers lequel envoyer le clic invisible.", null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='video_ad_strategy',
            field=models.CharField(choices=[('ALWAYS', 'Sur TOUTES les vidéos'), ('EVERY_3', 'Toutes les 3 vidéos uniquement'), ('DISABLED', 'Désactivé')], default='DISABLED', max_length=15),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='ad_clicks_before_video',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de clics réels sur le player requis avant de lancer la vidéo.'),
        ),
    ]
