# Generated by Django 6.0.4 on 2026-04-21 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_platformsettings_invisible_ad_active_and_more'),
        ('videos', '0004_category_affiliate_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam ou publicité'), ('INAPPROPRIATE', 'Contenu inapproprié / Adulte'), ('VIOLENCE', 'Violence ou haine'), ('COPYRIGHT', "Atteinte aux droits d'auteur"), ('OTHER', 'Autre raison')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Détails supplémentaires sur le signalement')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='videos.photo')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
