# Generated by Django 6.0.4 on 2026-04-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformsettings',
            options={'verbose_name': 'Configuration Générale', 'verbose_name_plural': 'Configuration Générale'},
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_chat',
            field=models.BooleanField(default=True, help_text='Activer la messagerie privée'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_member_upload',
            field=models.BooleanField(default=True, help_text="Permettre aux membres d'uploader"),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_social',
            field=models.BooleanField(default=True, help_text='Activer Amis, Profils, Likes'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='primary_color',
            field=models.CharField(default='#E6007E', help_text='Couleur principale (ex: #E6007E)', max_length=7),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='secondary_color',
            field=models.CharField(default='#000000', help_text='Couleur secondaire', max_length=7),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='site_slogan',
            field=models.CharField(blank=True, help_text='Slogan sous le logo', max_length=255),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='ad_clicks_before_video',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='invisible_ad_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='invisible_ad_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
