# Generated by Django 6.0.4 on 2026-05-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_platformsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_format',
            field=models.CharField(choices=[('HTML', 'HTML brute'), ('TEXT', 'Texte brut (sauts de ligne automatiques)')], default='HTML', help_text='Détermine si le contenu est interprété comme du code HTML brut ou du texte brut.', max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(help_text='Le contenu de la page (HTML ou Texte)'),
        ),
    ]
